# Site settings
title: Jekyons
version: "v1"
description: "Stop writing CSS and start building prototypes."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: joshosbrn
github_username:  joshosbrn

# Build settings
markdown: kramdown

exclude: [node_modules, gulpfile.js]
